kind: pipeline
name: MaestroCI Build Bot

steps:
- name: test
  image: ubuntu:rolling
  environment:
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    GH_REPO_NAME:
      from_secret: GH_REPO_NAME
  commands:
  - bash ./runner.sh
